[package]
name = "infra"
version = "0.1.0"
authors = ["Daniel Shiposha <mrshiposha@gmail.com>"]
edition = "2018"

[dependencies]
cc = { version = "1.0.61", features = ["parallel"] }
bindgen = "0.55.1"
shaderc = "0.6.3"
convert_case = "0.4.0"