#ifndef ___APRIORI2_APP_INFO_H___
#define ___APRIORI2_APP_INFO_H___

#define APRIORI2_APPLICATION_NAME "apriori2"
#define APRIORI2_MAJOR_VERION 0
#define APRIORI2_MINOR_VERION 1
#define APRIORI2_PATCH_VERION 0
#define APRIORI2_VK_VERSION \
    VK_MAKE_VERSION(APRIORI2_MAJOR_VERION, APRIORI2_MINOR_VERION, APRIORI2_PATCH_VERION)

#endif // ___APRIORI2_APP_INFO_H___